### PR TITLE
Ember 3 fix

### PR DESCRIPTION
**Pull request by zendern**
Once switching to ember 3 this caused the isGlimmer check to no longer be valid it then tried to use htmlbars which is not possible.

I believe this may be the issue that was being seen in https://github.com/AltSchool/ember-cli-react/issues/18

Once we upgraded to Ember 3 this was the error that was presented to us when trying to run our test suite. 
screen shot 2018-04-30 at 4 08 11 pm

### CODE REVIEW

**Comment by cah-nathanzender** [comment]
Not 100%....for got to update the ember version compatibility in this PR to validate the fix...working on that now but having dependency issues. Will have it shortly hopefully.

**Comment by zendern** [comment]
Not 100%....forgot to update the ember version compatibility in this PR to validate the fix...working on that now but currently having dependency issues. Will have it shortly hopefully.

**Comment by cah-nathanzender** [comment]
Tests now pass on numerous LTS 2.x and 3.x ember versions. Please let me know if this is acceptable since it now no longer runs again any of the 1.x releases.

**Comment by zendern** [comment]
Tests now pass on numerous LTS 2.x and 3.x ember versions. Please let me know if this is acceptable since it now no longer runs again any of the 1.x releases.

**Comment by zendern** [comment]
My reasoning was that Emberjs 1.13 was released back in 2015 so it seemed a little dated to me at this point but I can add it and see what shakes out if anything.

**Comment by alexgb** [comment]
Thanks @zendern. Figured we might as well keep 1.13 support until sometime forces us not to. Also, there may be folks out there using this addon to migrate older Ember apps to react.

**Pull request merged**
